### ISSUE TITLE
作者大大你好！！！

### ISSUE THREAD

**Issue by dejavunHui** [zanshuxun/WeChat_Big_Data_Challenge_DeepCTR_baseline#2]
请问这个为什么不做labelencoder，这样不是比较省空间吗，我做完了发现效果竟然没有不做的好，求解答

**Comment by zanshuxun** [comment]
1、
> 请问这个为什么不做labelencoder，这样不是比较省空间吗

我当时没做labelencoder是因为我看id都已经是排序过的了

2、

> 我做完了发现效果竟然没有不做的好

做这个为啥会对效果有影响？你都说了是省空间
