### ISSUE TITLE
task_dnn_units error

### ISSUE THREAD

**Issue by librauee** [zanshuxun/WeChat_Big_Data_Challenge_DeepCTR_baseline#3]
I can not use the parameter task_dnn_units, here is the error when i set task_dnn_units =(128, 128)
```
TypeError: issubclass() arg 1 must be a class
```

Can you tell me how to solve it?

**Comment by zanshuxun** [comment]
This error has been solved by 45598b50931a15bb7f28a82e454108bc35377d50 in 25 May. You can use the new version or simply change the corresponding line according to 45598b50931a15bb7f28a82e454108bc35377d50.

**Comment by librauee** [comment]
Thanks!
